
SPROFCOMMAND=sprofilev5

BLOCKSIZE=( 1024 2048 10240 20480 30720 40960 65536 131072 262144 524288)
#BLOCKSIZE=( 1048576 2097152)
NOBLOCKS=512
TAPCHANGE=10
TAPCHANGEINTERVAL=128
for i in "${BLOCKSIZE[@]}"
do
	SPROFFILENAME="sprofv5_"$NOBLOCKS"_"$i"_"$TAPCHANGE"_"$TAPCHANGEINTERVAL".csv"
	$SPROFCOMMAND -o $SPROFFILENAME -w ./ ./bin/amd/fir_tap_change $NOBLOCKS $i $TAPCHANGE $TAPCHANGEINTERVAL
done


#TAPCHANGEINTERVAL=15
#for i in "${BLOCKSIZE[@]}"
#do
#        SPROFFILENAME="sprofv3_"$NOBLOCKS"_"$i"_"$TAPCHANGE".csv"
#        $SPROFCOMMAND -o $SPROFFILENAME ./bin/amd/fir_tap_change $NOBLOCKS $i $TAPCHANGE $TAPCHANGEINTERVAL
#done


#TAPCHANGEINTERVAL=10
#for i in "${BLOCKSIZE[@]}"
#do
#        SPROFFILENAME="sprofv3_"$NOBLOCKS"_"$i"_"$TAPCHANGE".csv"
#        $SPROFCOMMAND -o $SPROFFILENAME ./bin/amd/fir_tap_change $NOBLOCKS $i $TAPCHANGE $TAPCHANGEINTERVAL
#done

