# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='fir.proto',
  package='fir',
  serialized_pb='\n\tfir.proto\x12\x03\x66ir\"!\n\x05stage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\"H\n\x08pipeline\x12\x1d\n\tfir_stg_1\x18\x01 \x01(\x0b\x32\n.fir.stage\x12\x1d\n\tfir_stg_2\x18\x02 \x01(\x0b\x32\n.fir.stage')




_STAGE = descriptor.Descriptor(
  name='stage',
  full_name='fir.stage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='fir.stage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='fir.stage.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=51,
)


_PIPELINE = descriptor.Descriptor(
  name='pipeline',
  full_name='fir.pipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fir_stg_1', full_name='fir.pipeline.fir_stg_1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fir_stg_2', full_name='fir.pipeline.fir_stg_2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=125,
)

_PIPELINE.fields_by_name['fir_stg_1'].message_type = _STAGE
_PIPELINE.fields_by_name['fir_stg_2'].message_type = _STAGE
DESCRIPTOR.message_types_by_name['stage'] = _STAGE
DESCRIPTOR.message_types_by_name['pipeline'] = _PIPELINE

class stage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STAGE
  
  # @@protoc_insertion_point(class_scope:fir.stage)

class pipeline(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PIPELINE
  
  # @@protoc_insertion_point(class_scope:fir.pipeline)

# @@protoc_insertion_point(module_scope)
